version: "3.7"
services:
  epaas:
    container_name: epaas
    image: harbor.bingjunx.com/epaas/epaas
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "100m"
    environment:
      - ADMIN_PORT=8080
    ports:
      - 5000:5000/tcp
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime